name: Goals
options:
  postGenCommand: source scripts/update_pods.sh
  deploymentTarget:
    iOS: 16.0

attributes:
  organizationname: LiamGuedes

configs:
  debug: development
  test: development
  release: release

settings:
  configs:
    test:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG TEST

targets:
  Goals:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    preBuildScripts: source scripts/swiftlint.sh
    settings:
      base: 
        INFOPLISTFILE: Goals/Info.plist
        ENABLE_BITCODE: NO
        PRODUCT_BUNDLE_IDENTIFIER: liamguedes.${PRODUCT_NAME}
        SDKROOT: iphoneos
        SWIFT_VERSION: 5.0
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        TARGETED_DEVICE_FAMILY: "1"
        PRODUCT_NAME: Goals
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: Iphone Developer
        


